### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by alin-simionoiuDE** [wbrefvem/go-bitbucket#12]
A simple example would go a long way to figure out how to use this. right now honestly i can't figure it out

**Comment by kolima** [comment]
For example, https://github.com/wbrefvem/jx/blob/98689a19328e78d5b600d43c453c1b01f54202d9/pkg/gits/bitbucket_cloud.go

**Comment by alin-simionoiuDE** [comment]
perfect! thank you
